spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:./data/myDB;FILE_LOCK=NO'
    username: sa
    password:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
  flyway:
    baselineOnMigrate: true
    enabled: true
    locations: classpath:db/migrations
server:
  port: 8080